logicalclocks/epipe-chef

- recipes/install.rb
https://hopshadoop.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-203
> [HOPSWORKS-203] Make sure libcurl.so.4 is installed on the machine where ePipe runs

- recipes/default.rb
https://github.com/hopshadoop/hops-testing/pull/20
> HOPSWORKS-382 

- attributes/default.rb
- templates/default/start-epipe.sh.erb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-565
> [HOPSWORKS-565] Upgrade ePipe to 0.5

- recipes/default.rb
- templates/default/reindex-epipe.sh.erb
Call epipe reindex in case it is requested by cluster-defn. Useful when upgrading Hopsworks cluster.
> HOPSWORKS-757

- recipes/default.rb
- templates/default/epipe.service.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1091
> [HOPSWORKS-1091] Add systemd unit file deps

- templates/default/config.ini.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1221
> [HOPSWORKS-1221][ePipe] Add metrics endpoint

- attributes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1250
> [HOPSWORKS-1250] Bump ePipe version to 0.10

- templates/default/config-reindex.ini.erb
- templates/default/config.ini.erb
jira - https://logicalclocks.atlassian.net/browse/HOPSWORKS-1459
> [HOPSWORKS-1459] provenance support - file and app

- attributes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1308
tests: https://github.com/logicalclocks/hops-testing/pull/598
> [HOPSWORKS-1308][ePipe] Rewrite and fix the metrics code

- recipes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1306
tests: https://github.com/logicalclocks/hops-testing/pull/603
> [HOPSWORKS-1306][ePipe] Add support for HA Elasticsearch

- templates/default/reindex-epipe.sh.erb
- templates/default/start-epipe.sh.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1608
tests: https://github.com/logicalclocks/hops-testing/pull/640
> [HOPSWORKS-1608][ePipe] Change the epipe log file to include current date and time

- attributes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1609
tests: https://github.com/logicalclocks/hops-testing/pull/645
> [HOPSWORKS-1609][ePipe] Fix version conflicts in Elasticsearch

- attributes/default.rb
- templates/default/config-reindex.ini.erb
- templates/default/config.ini.erb
- templates/default/reindex-epipe.sh.erb
- templates/default/start-epipe.sh.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1618
> [HOPSWORKS-1618][ePipe] Use boost::log library to implement proper logging

- recipes/default.rb
- templates/default/config-reindex.ini.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1770
> [HOPSWORKS-1770] reindex featurestore index

- attributes/default.rb
- metadata.rb
- recipes/default.rb
- recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1694
> [HOPSWORKS-1694] run user code in docker

- recipes/default.rb
tests: https://github.com/logicalclocks/hops-testing-ee/pull/110
> [HOPSWORKS-1862] Fix cyclic dependency error

- attributes/default.rb
- metadata.rb
- recipes/default.rb
- templates/default/config-reindex.ini.erb
- templates/default/config.ini.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1657
> [HOPSWORKS-1657] System users x.509 v2

- templates/default/epipe.service.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
> [HOPSWORKS-2065] Automatically restart failed systemd units

- templates/default/epipe.service.erb
* [HOPSWORKS-2065] Automatically restart failed systemd units
* [HOPSWORKS-2065] Fix burst
[HOPSWORKS-2065]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
[HOPSWORKS-2065]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
> [HOPSWORKS-2065] Automatically restart failed systemd units (#47)

- attributes/default.rb
- templates/default/config.ini.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2404
> [HOPSWORKS-2404] remove metadata designer 

- attributes/default.rb
- recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2578
> [HOPSWORKS-2578] Logs to data volume

- Karamelfile
- attributes/default.rb
- recipes/install.rb
- templates/default/config-reindex.ini.erb
- templates/default/config.ini.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2763
> [HOPSWORKS-2763] Upgrade to Opensearch

- attributes/default.rb
https://hopsworks.atlassian.net/browse/HOPSWORKS-3184
> [HOPSWORKS-3184] feature view search 

- attributes/default.rb
- templates/default/stop-epipe.sh.erb
https://hopsworks.atlassian.net/browse/HWORKS-659
> [HWORKS-659] Configurable pid directory
